### PR TITLE
I101 - plot inputs using first90 functions

### PR DESCRIPTION
**Pull request by hillalex**
Depends on https://github.com/mrc-ide/shiny90/pull/23 so please merge that one first.

This breaks down the input review plot into individual plots, using functions from `first90`

### CODE REVIEW

**Review by MartinEden — CHANGES_REQUESTED** [review]
I get using the individual functions for rendering pjnz plots on the spectrum files tab.

But why have you added all the spectrum plots to the input review tab? I thought that tab was for survey and program data plots? Have you heard differently?

**Comment by hillalex** [comment]
I just figured the review input data was for all inputs, so pjnz, survey and program?

**Comment by MartinEden** [comment]
I'd kind of figured that since we had shown the review figures for PJNZ files on the PJNZ tab we didn't need to repeat them. But since the tables for survey and program data use up a lot of screen space it was better to have a separate tab for reviewing those?

At the end of the day, I think it's up to us to provide good UX, and I'm happy to trust your decision either way.

**Comment by hillalex** [comment]
I've changed the order so the other graphs appear first, but i'm inclined to leave the 4 repeated graphs on the review inputs tab, for completeness.

**Review by MartinEden — APPROVED** [review]

**Comment by MartinEden** [comment]
Just waiting for tests to pass.

**Pull request merged**
